name: NodeJS CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm ci
        npm run build --if-present
        touch .env
        echo "${{ secrets.PROD_ENV_FILE }}" > .env
        
    - name: rsync deployments
      uses: burnett01/rsync-deployments@7.0.2
      with:
        switches: -avzr --delete
        path: ./*
        remote_path: /var/www/my-app/
        remote_host: ec2-13-49-170-200.eu-north-1.compute.amazonaws.com
        remote_user: ubuntu
        remote_key: "${{ secrets.PITLAP_SSH }}"
