name: NodeJS CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm ci
        npm run build --if-present
        touch dist/src/.env
        echo '${{ secrets.PITLAP_ENV }}' >> dist/src/.env
        echo '${{ secrets.PERPLEXITY_API_KEY }}' >> dist/src/.env
        echo '${{ secrets.WEATHER_API_KEY }}' >> dist/src/.env
        echo '${{ secrets.YT_DATA_API_KEY }}' >> dist/src/.env
        echo '${{ secrets.FIR_SERVICE_ACCOUNT }}' >> dist/src/pitlap_fir.json
        echo '${{ secrets.FIR_SERVICE_ACCOUNT_URL }}' >> dist/src/.env

    - name: rsync deployments
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Only run deployment on push to main
      uses: burnett01/rsync-deployments@7.0.2
      with:
        switches: -avzr --delete --include='.env' --exclude='.git*'
        path: ./*
        remote_path: /var/www/pitlap/
        remote_host: "${{ secrets.PITLAP_HOST }}"
        remote_user: ubuntu
        remote_key: "${{ secrets.PITLAP_SSH }}"
